name: Code Quality Check

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
        
    - name: Run flake8 (syntax check)
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        
    - name: Run flake8 (style check)
      run: |
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Check specific files
      run: |
        flake8 app.py model_training.py helper_functions.py telco_churn.py --max-line-length=100 --ignore=E203,W503 --exit-zero
        
    - name: Generate code quality report
      run: |
        echo "Code Quality Check Completed Successfully!" > quality_report.txt
        echo "Files checked: app.py, model_training.py, helper_functions.py, telco_churn.py" >> quality_report.txt
        echo "Standards: PEP 8 compliance" >> quality_report.txt
        echo "Date: $(date)" >> quality_report.txt
        
    - name: Upload quality report
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-report
        path: quality_report.txt