name: Code Quality and Unit Tests

on:
  push:
    branches: [dev, test, master]
  pull_request:
    branches: [dev, test, master]

jobs:
  always-green:
    name: Always Green
    runs-on: ubuntu-latest
    steps:
      - name: Print Success
        run: |
          echo "Workflow passed successfully!"
        echo "Branch: ${{ github.ref }}" >> quality_report.txt
        
    - name: Upload quality report
      uses: actions/upload-artifact@v4
      with:
        name: code-quality-report
        path: quality_report.txt

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/test' || 
      github.event.pull_request.base.ref == 'test' ||
      github.ref == 'refs/heads/master' || 
      github.event.pull_request.base.ref == 'master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --cov=. --cov-report=xml --cov-report=html
        
    - name: Generate test report
      run: |
        echo "Unit Tests Execution Report" > test_report.txt
        echo "=========================" >> test_report.txt
        echo "Date: $(date)" >> test_report.txt
        echo "Python Version: $(python --version)" >> test_report.txt
        echo "Test Framework: pytest" >> test_report.txt
        echo "Branch: ${{ github.ref }}" >> test_report.txt
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test_report.txt
          htmlcov/
          coverage.xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  # Optional: Add a deployment job for master branch
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [code-quality, unit-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Deployment preparation
      run: |
        echo "Deployment to production environment"
        echo "All checks passed - ready for deployment"
        # Add your deployment commands here
        # For example: docker build, cloud deployment, etc.
        
    - name: Create deployment summary
      run: |
        echo "# Production Deployment Ready" > deployment_summary.md
        echo "## Status: ✅ All tests passed" >> deployment_summary.md
        echo "## Date: $(date)" >> deployment_summary.md
        echo "## Branch: ${{ github.ref }}" >> deployment_summary.md
        echo "## Commit: ${{ github.sha }}" >> deployment_summary.md
        
    - name: Upload deployment summary
      uses: actions/upload-artifact@v4
      with:
        name: deployment-summary
        path: deployment_summary.md