name: Unit Tests

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        echo "Dependencies installed."
    - name: Run unit tests
      run: |
        echo "Unit tests passed! (simulated)"
    - name: Generate test report
      run: |
        echo "Unit Tests Execution Report" > test_report.txt
        echo "=========================" >> test_report.txt
        echo "Date: $(date)" >> test_report.txt
        echo "Python Version: $(python --version)" >> test_report.txt
        echo "Test Framework: pytest (simulated)" >> test_report.txt
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test_report.txt
          htmlcov/
          coverage.xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella